FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Web-engineering-team6 API

画像をjson形式で入力したら数値が帰ってくるという形はいかがでしょうか。

## FaceAnalysis [/face_analysis]

### Face Analysis [GET]

+ Request JSON Message

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        [
            {
                "return": "何かしらの画像？",
                "published_at": "2015-08-05T08:40:51.620Z",
            }
        ]