FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Web-engineering-team6 API

## FaceAnalysis [/face_analysis/imageAnalysis{?imageId,analysisType}]

### Face Analysis [GET]

* imgフォルダーにimageIDの名前で画像を保存してください。
* analysisTypeにsourceやanimelなどを入れてください。

+ Parameters

    + imageId: 000001 (number, required)
    + analysisType: source (string, required)

+ Response 200 (application/json)

        + Attributes
            + faceComponent (required)
                + solty : 0.8 (number, required)
                + soysource : 0.15 (number, required)
                + source : 0.05 (number, required)
                
+ Response 403 (application/json)