FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Web-engineering-team6 API

## FaceAnalysis [/v1/faceAnalysis{?imageId,analysisType}]

### Face Analysis [GET]

* imgフォルダーにimageID.pngの名前で画像を保存してください。
* analysisTypeにsourceやanimalなどを入れてください。

+ Parameters

    + imageId: 000001 (number, required)
    + analysisType: source (string, required)

+ Response 200 (application/json)

        [
            {
                'attributeName1': 'solty',
                'attribute1': 0.8
            },
            {
                'attributeName2': 'soysource',
                'attribute2': 0.15
            },
            {
                'attributeName3': 'source',
                'attribute2': 0.05
            }
        ]
    
+ Response 400 (application/json)

## ChangeFace [/v1/changeFace]

### Chage Face [POST]

* imgフォルダーにimageID.pngの名前で画像を保存してください。

+ Request (application/json)

        {
            "eachParameterValue": [
                1.23,
                2.34,
                3.45,
                6.78
            ]
        }

+ Response 200 (application/json)

        [
            {
                'chagedImagePath': 'img/xxxxxx.png'
            }
        ]
        
+ Response 400 (application/json)

+ Response 500 (application/json)